version: 1.3.0.{build}
image: Visual Studio 2019
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
platform: Any CPU
before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: normal
after_build:
- cmd: >-
    del /f pporise\bin\Release\*.pdb

    del /f pporise\bin\Release\*.xml


    type nul > ReadMe.txt

    echo Sample-Scripts: https://tmearn.com/es0ni0V > pporise/bin/Release/ReadMe.txt

    echo Discord Link: https://discord.gg/akxSZ9X >> pporise/bin/Release/ReadMe.txt
artifacts:
- path: pporise\bin\Release
  name: "PPORise-Release"