# version format
version: 1.2.{build}

# VS Version
image: Visual Studio 2017

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
- cmd: appveyor-retry nuget restore
build:
  verbosity: normal
after_build:
- cmd: >-
    del /f pporise\bin\Release\*.pdb

    del /f pporise\bin\Release\*.xml


    type nul > ReadMe.txt

    echo Sample-Scripts: http://tmearn.com/es0ni0V > pporise/bin/Release/ReadMe.txt

    echo Discord Link: https://discord.gg/akxSZ9X >> pporise/bin/Release/ReadMe.txt
artifacts:
- path: pporise\bin\Release
  name: PPORise-{version}