using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Network
{
    public class HttpConnection
    {
        public event Action<string, string, string> LoggedIn;
        public event Action<Exception> LoggingError;

        public readonly HttpClient Client;

        public string Id { get; private set; }
        public string Username { get; private set; }
        public string HashPassword { get; private set; }


        private const string LoginWebUrl = "http://pokemon-planet.com/forums/index.php?action=login2";
        private const string UserInfoUrl = "http://www.pokemon-planet.com/getUserInfo.php";

        private CookieContainer _cookieContainer { get; set; }

        public bool IsLoggedIn { get; set; }

        public HttpConnection()
        {
            _cookieContainer = new CookieContainer();
            Client = new HttpClient(new HttpClientHandler
            {
                CookieContainer = _cookieContainer
            })
            {
                Timeout = new TimeSpan(0, 0, 0, 5)
            };
        }

        public HttpConnection(string host, int port)
        {
            _cookieContainer = new CookieContainer();
            Client = new HttpClient(new HttpClientHandler
            {
                UseProxy = true,
                Proxy = new WebProxy($"{host}:{port}"),
                CookieContainer = _cookieContainer
            })
            {
                Timeout = new TimeSpan(0, 0, 0, 5)
            };
        }

        public async Task PostLogin(string user, string pass)
        {
            try
            {
                var values = new Dictionary<string, string>
                {
                    { "user", "Iambetter" },
                    { "passwrd", "Iambetter" },
                    { "cookielength", "-1" }
                };

                var content = new FormUrlEncodedContent(values);

                var result = await SendPost(content, LoginWebUrl);

                var response = await SendGet(UserInfoUrl);

                if (response is null is false)
                {
                    if (response.StatusCode == HttpStatusCode.Accepted || response.StatusCode == HttpStatusCode.OK)
                    {
                        var getResponse = await response.Content.ReadAsStringAsync();
                        if (!string.IsNullOrEmpty(getResponse))
                        {
                            var responsePars = getResponse
                                .Split('&');
                            if (responsePars.Length > 2)
                            {
                                var data1 = responsePars[0].Split('=');
                                var data2 = responsePars[1].Split('=');
                                var data3 = responsePars[2].Split('=');
                                if (data1.Length > 0 && data2.Length > 0 && data3.Length > 0)
                                {
                                    Id = data1[1];
                                    Username = data2[1];
                                    HashPassword = data3[1];
                                    Console.WriteLine(Id + "-" + Username + "-" + HashPassword);
                                    IsLoggedIn = true;
                                    return;
                                }
                            }
                        }
                    }
                    IsLoggedIn = false;
                    LoggingError?.Invoke(null);
                }
            }
            catch (Exception ex)
            {
                IsLoggedIn = false;
                LoggingError?.Invoke(ex);
            }
        }

        private async Task<HttpResponseMessage> SendPost(FormUrlEncodedContent content, string url)
        {
            var cookieContainer = _cookieContainer;
            //HttpClientHandler handler = null;
            //if (_port != -1 && !string.IsNullOrEmpty(_host))
            //    handler = new HttpClientHandler { UseProxy = true, Proxy = new WebProxy($"{_host}:{_port}"), CookieContainer = cookieContainer };
            //else
            //    handler = new HttpClientHandler { CookieContainer = cookieContainer };

            //using (var client = new HttpClient(handler, true))
            //{

            //}
            var message = new HttpRequestMessage(HttpMethod.Post, url) { Content = content };

            // Header stuff
            //Following like Mozilla FireFox ;).. I suggest not to touch anything below coz all info were generated by FireFox..
            message.Headers.Add("Host", "pokemon-planet.com");
            message.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0");
            message.Headers.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
            message.Headers.Add("Accept-Language", "en-US;q=0.5,en;q=0.3");
            message.Headers.Add("Referer", "http://pokemon-planet.com/"); // default base url is http://pokemon-planet.com/ you can change according to your need...
            message.Headers.Add("Proxy-Authorization", "Basic SEZhNjQ2NjQyZTJlMDZjYjM0NWZkYzAyOGU3YTM0YjYwMS5oNzgzb2hhdzA5amRmMDpIRmE2NDY2NDJlMmUwNmNiMzQ1ZmRjMDI4ZTdhMzRiNjAxLmg3ODIzOWhk");
            message.Headers.Add("Connection", "keep-alive");
            message.Headers.Add("Cookie", "__cfduid=d72c26c761f3d8c0bc799ea6816ad62661543274330; cf_clearance=5802ba46b8530fdcb66ffecd27c90e3cc6610c94-1543274508-86400-250");
            message.Headers.Add("Upgrade-Insecure-Requests", "1");

            //Cookie stuff
            cookieContainer.Add(new Cookie("__cfduid", "d72c26c761f3d8c0bc799ea6816ad62661543274330", "/", ".pokemon-planet.com") { Expires = DateTime.Parse("2026-11-19T23:02:55.000Z") }); // we can update the expire date as we want :D
            cookieContainer.Add(new Cookie("cf_clearance", "5802ba46b8530fdcb66ffecd27c90e3cc6610c94-1543274508-86400-250", "/", ".pokemon-planet.com"));

            //sending those datas...
            var result = await Client.SendAsync(message);
            result.EnsureSuccessStatusCode();

            return result;
        }

        private async Task<HttpResponseMessage> SendGet(string url)
        {
            var cookieContainer = _cookieContainer;

            //HttpClientHandler handler = null;
            //if (_port != -1 && !string.IsNullOrEmpty(_host))
            //    handler = new HttpClientHandler { UseProxy = true, Proxy = new WebProxy($"{_host}:{_port}"), CookieContainer = cookieContainer };
            //else
            //    handler = new HttpClientHandler { CookieContainer = cookieContainer };

            //using (var client = new HttpClient(handler, true))
            //{

            //}
            var message = new HttpRequestMessage(HttpMethod.Get, url);

            // Header stuff
            //Following like Mozilla FireFox ;).. I suggest not to touch anything below coz all info were generated by FireFox..
            message.Headers.Add("Host", "pokemon-planet.com");
            message.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0");
            message.Headers.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
            message.Headers.Add("Accept-Language", "en-US;q=0.5,en;q=0.3");
            message.Headers.Add("Referer", "http://pokemon-planet.com/"); // default base url is http://pokemon-planet.com/ you can change according to your need...
            message.Headers.Add("Proxy-Authorization", "Basic SEZhNjQ2NjQyZTJlMDZjYjM0NWZkYzAyOGU3YTM0YjYwMS5oNzgzb2hhdzA5amRmMDpIRmE2NDY2NDJlMmUwNmNiMzQ1ZmRjMDI4ZTdhMzRiNjAxLmg3ODIzOWhk");
            message.Headers.Add("Connection", "keep-alive");
            message.Headers.Add("Cookie", "__cfduid=d72c26c761f3d8c0bc799ea6816ad62661543274330; cf_clearance=5802ba46b8530fdcb66ffecd27c90e3cc6610c94-1543274508-86400-250");
            message.Headers.Add("Upgrade-Insecure-Requests", "1");

            //Cookie stuff
            cookieContainer.Add(new Cookie("__cfduid", "d72c26c761f3d8c0bc799ea6816ad62661543274330", "/", ".pokemon-planet.com") { Expires = DateTime.Parse("2026-11-19T23:02:55.000Z") }); // we can update the expire date as we want :D
            cookieContainer.Add(new Cookie("cf_clearance", "5802ba46b8530fdcb66ffecd27c90e3cc6610c94-1543274508-86400-250", "/", ".pokemon-planet.com"));

            //sending those datas...
            var result = await Client.SendAsync(message);
            result.EnsureSuccessStatusCode();

            return result;
        }
    }
}
